
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { UserPlus, ChevronDown, KeyRound, Loader2, ShieldAlert } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { GRADE_LEVELS } from "@/lib/constants";
import { Textarea } from "@/components/ui/textarea";
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import React, { useState } from "react";
import { getSupabase } from "@/lib/supabaseClient";
import type { AuthError } from "@supabase/supabase-js";

const teacherSchema = z.object({
  fullName: z.string().min(3, "Full name must be at least 3 characters."),
  email: z.string().email("Invalid email address."),
  password: z.string().min(6, "Password must be at least 6 characters for Supabase Auth."),
  confirmPassword: z.string(),
  subjectsTaught: z.string().min(3, "Please list at least one subject area."),
  contactNumber: z.string().min(10, "Contact number must be at least 10 digits.").regex(/^\+?[0-9\\s-()]+$/, "Invalid phone number format."),
  assignedClasses: z.array(z.string()).min(1, "At least one class must be assigned."),
}).refine(data => data.password === data.confirmPassword, {
  message: "Passwords don't match",
  path: ["confirmPassword"],
});

type TeacherFormData = z.infer<typeof teacherSchema>;

// Interface for data being sent to Supabase 'teachers' table
interface TeacherSupabaseData {
  auth_user_id: string; // Stores the Supabase Auth user ID
  full_name: string;
  email: string; 
  contact_number: string;
  subjects_taught: string;
  assigned_classes: string[];
  // 'password' column is no longer needed here as Supabase Auth handles it.
  // 'id' (PK) is auto-generated by Supabase for this table.
}

export default function RegisterTeacherPage() {
  const { toast } = useToast();
  const supabase = getSupabase();
  const [selectedClasses, setSelectedClasses] = useState<string[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<TeacherFormData>({
    resolver: zodResolver(teacherSchema),
    defaultValues: {
      fullName: "",
      email: "",
      password: "",
      confirmPassword: "",
      subjectsTaught: "",
      contactNumber: "",
      assignedClasses: [],
    },
  });

  const handleClassToggle = (grade: string) => {
    const newSelectedClasses = selectedClasses.includes(grade)
      ? selectedClasses.filter((c) => c !== grade)
      : [...selectedClasses, grade];
    setSelectedClasses(newSelectedClasses);
    form.setValue("assignedClasses", newSelectedClasses, { shouldValidate: true });
  };

  const onSubmit = async (data: TeacherFormData) => {
    setIsSubmitting(true);
    
    try {
      // 1. Create Supabase Auth user
      const { data: authData, error: authError } = await supabase.auth.signUp({
        email: data.email,
        password: data.password,
        options: {
          data: { // Store full_name in user_metadata in auth.users
            full_name: data.fullName,
          }
        }
      });

      if (authError) {
        console.error("RegisterTeacherPage: Supabase Auth signUp error:", authError);
        let userMessage = "Could not create teacher's authentication account.";
        if (authError.message.includes("User already registered") || authError.message.includes("already exists")) {
            userMessage = "This email address is already registered as an authentication user.";
            form.setError("email", { type: "manual", message: userMessage });
        } else if (authError.message.includes("Password should be at least 6 characters")) {
            userMessage = "The password is too weak for Supabase Auth.";
        } else if (authError.message.toLowerCase().includes("rate limit exceeded")) {
            userMessage = "Too many registration attempts. Please try again later.";
        } else {
            userMessage = authError.message;
        }
        toast({ title: "Auth Creation Failed", description: userMessage, variant: "destructive" });
        setIsSubmitting(false);
        return;
      }

      if (!authData.user) {
        toast({ title: "Auth Creation Issue", description: "Authentication user was not created, but no specific error returned. Please check Supabase logs.", variant: "destructive" });
        setIsSubmitting(false);
        return;
      }
      
      const authUserId = authData.user.id;

      // 2. Create teacher profile in 'teachers' table, linking to auth_user_id
      const teacherProfileToSave: TeacherSupabaseData = {
        auth_user_id: authUserId,
        full_name: data.fullName,
        email: data.email, // Store email here too for easier querying if needed
        contact_number: data.contactNumber,
        subjects_taught: data.subjectsTaught,
        assigned_classes: data.assignedClasses,
      };

      const { data: insertedProfileData, error: profileInsertError } = await supabase
        .from("teachers")
        .insert([teacherProfileToSave])
        .select()
        .single();

      if (profileInsertError) {
        console.error("RegisterTeacherPage: Supabase error inserting teacher profile:", profileInsertError);
        // Attempt to delete the auth user if profile creation fails to avoid orphaned auth users
        await supabase.auth.admin.deleteUser(authUserId); 
        console.warn("RegisterTeacherPage: Rolled back Supabase Auth user due to profile insert failure.");
        
        let userMessage = "Could not save teacher profile details after auth creation.";
         if (profileInsertError.message.includes("duplicate key value violates unique constraint")) {
            if (profileInsertError.message.includes("teachers_email_key")) { // Assuming you have a unique constraint on email in teachers table
                userMessage = "This email address is already linked to a teacher profile.";
                form.setError("email", { type: "manual", message: userMessage });
            } else if (profileInsertError.message.includes("unique_auth_user_id")) { // If you added a unique constraint on auth_user_id
                userMessage = "This authentication ID is already linked to a teacher profile.";
            } else {
                userMessage = "A teacher with similar unique details might already exist in the profiles table.";
            }
        } else {
            userMessage = profileInsertError.message;
        }
        toast({ title: "Profile Creation Failed", description: userMessage, variant: "destructive" });
        setIsSubmitting(false);
        return;
      }

      toast({
        title: "Teacher Registered Successfully!",
        description: `Teacher ${data.fullName} registered with Supabase Auth and profile created. They may need to confirm their email.`,
      });
      form.reset();
      setSelectedClasses([]);

    } catch (error: any) {
      console.error("RegisterTeacherPage: General error during teacher registration:", error);
      toast({
        title: "Registration Failed",
        description: `An unexpected error occurred: ${error.message}`,
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-6">
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="flex items-center text-2xl font-headline">
            <UserPlus className="mr-2 h-6 w-6" /> Register New Teacher
          </CardTitle>
          <CardDescription>
            Creates a Supabase Authentication user and a profile in the 'teachers' table.
            Teachers will log in using these credentials. Email confirmation may be required by Supabase.
          </CardDescription>
        </CardHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)}>
            <CardContent className="space-y-4">
              <FormField control={form.control} name="fullName" render={({ field }) => (
                  <FormItem><FormLabel>Full Name</FormLabel>
                    <FormControl><Input placeholder="Enter teacher's full name" {...field} /></FormControl>
                  <FormMessage /></FormItem>)} />
              <FormField control={form.control} name="email" render={({ field }) => (
                  <FormItem><FormLabel>Email Address (for Login)</FormLabel>
                    <FormControl><Input type="email" placeholder="teacher@example.com" {...field} /></FormControl>
                  <FormMessage /></FormItem>)} />
              <div className="grid md:grid-cols-2 gap-4">
                <FormField control={form.control} name="password" render={({ field }) => (
                    <FormItem><FormLabel className="flex items-center"><KeyRound className="mr-1 h-4 w-4"/>Password</FormLabel>
                      <FormControl><Input type="password" placeholder="Create a password" {...field} /></FormControl>
                    <FormMessage /></FormItem>)} />
                <FormField control={form.control} name="confirmPassword" render={({ field }) => (
                    <FormItem><FormLabel>Confirm Password</FormLabel>
                      <FormControl><Input type="password" placeholder="Confirm your password" {...field} /></FormControl>
                    <FormMessage /></FormItem>)} />
              </div>
              <FormField control={form.control} name="subjectsTaught" render={({ field }) => (
                  <FormItem><FormLabel>Main Subjects Taught</FormLabel>
                    <FormControl><Textarea placeholder="e.g., Mathematics, English Language" {...field} /></FormControl>
                  <FormMessage /></FormItem>)} />
              <FormField control={form.control} name="contactNumber" render={({ field }) => (
                  <FormItem><FormLabel>Contact Number</FormLabel>
                    <FormControl><Input placeholder="Enter teacher's contact number" {...field} /></FormControl>
                  <FormMessage /></FormItem>)} />
              <FormField control={form.control} name="assignedClasses" render={({ field }) => (
                  <FormItem className="flex flex-col"><FormLabel>Assign Classes</FormLabel>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="outline" className="justify-between">
                          {selectedClasses.length > 0 ? `${selectedClasses.length} class(es) selected` : "Select classes"}
                          <ChevronDown className="ml-2 h-4 w-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent className="w-full max-h-60 overflow-y-auto">
                        <DropdownMenuLabel>Available Grade Levels</DropdownMenuLabel><DropdownMenuSeparator />
                        {GRADE_LEVELS.map((grade) => (
                          <DropdownMenuCheckboxItem key={grade} checked={selectedClasses.includes(grade)} onCheckedChange={() => handleClassToggle(grade)} onSelect={(e) => e.preventDefault()}>
                            {grade}
                          </DropdownMenuCheckboxItem>))}
                      </DropdownMenuContent>
                    </DropdownMenu><FormMessage /></FormItem>)} />
            </CardContent>
            <CardFooter>
              <Button type="submit" className="w-full sm:w-auto" disabled={isSubmitting}>
                {isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : "Register Teacher"}
              </Button>
            </CardFooter>
          </form>
        </Form>
      </Card>
       <Card className="mt-4 border-amber-500 bg-amber-500/10">
        <CardHeader><CardTitle className="text-amber-700 flex items-center"><ShieldAlert className="mr-2"/> Important Note for Admin</CardTitle></CardHeader>
        <CardContent className="text-sm text-amber-600 space-y-2">
            <p>After registration, the teacher will receive a confirmation email from Supabase if email confirmations are enabled in your Supabase project settings (Authentication &gt; Settings &gt; Email templates).</p>
            <p>Ensure the `auth_user_id UUID` column has been added to your `public.teachers` table in Supabase before registering teachers.</p>
        </CardContent>
      </Card>
    </div>
  );
}
